Update to latest npm modules
Betterment/test_track_js_client pull request #60
Opened 2023-08-28 18:41 UTC by jesseproudman

Updates many libraries to latest versions eliminating issues via `yarn audit` and warnings packaging.

2023-08-28 18:58 UTC, jesseproudman commented
Doesn't appear that there's `ci` here but the following pass locally:

```
yarn lint
yarn jest
yarn build
```

2023-08-31 16:07 UTC, jesseproudman commented
@zerodom30 I can not. I don't have permissions on the repo. I think @smudge maybe can?

2023-08-31 16:08 UTC, zerodom30 commented
@jesseproudman no problem I tagged him

2023-08-31 18:53 UTC, dfranco65 approved these changes
domain checkride lgtm

2023-09-01 14:58 UTC, zerodom30 requested changes
The eslint errors should be resolved instead of ignored since it does provide needed improvements to the tests. 
[expect expect rule](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/expect-expect.md#enforce-assertion-to-be-made-in-a-test-body-expect-expect)
[jest/no-done-callback](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-done-callback.md)

2023-09-01 14:58 UTC, zerodom30 commented on src/mixpanelAnalytics.test.js
>      it('calls window.mixpanel.track()', done => {
The fix for the eslint error, just use an anonymous callback and delete the call to`done`. 
```suggestion
    it('calls window.mixpanel.track()', () => {
```

2023-09-01 14:58 UTC, zerodom30 commented on src/session.test.js
>        it('calls the correct vary function for the given split', done => {
There should be an `expect` assertion in this test.

2023-09-01 17:44 UTC, jesseproudman commented
@zerodom30 I don't know how to fix those specs -- I've given it a shot but get more errors. Could you give them a shot? You're welcome to push to the branch.

2023-09-06 17:55 UTC, jesseproudman commented
@zerodom30 Was able to fix the specs this morning. This should be good to go now.

2023-09-06 20:19 UTC, zerodom30 approved these changes
platformLGTM

2023-09-06 20:21 UTC, jesseproudman commented
@zerodom30 Looks like we've got an old policy bot configuration that's pointing at the wrong branch?

2023-09-06 20:33 UTC, DanC5 approved these changes
domain lgtm

2023-09-07 17:06 UTC, smudge commented
> isn't that because this is a fork of the original repo

I'm not sure that the issue is that the PR comes from a fork -- all our public repos are set up with a forking model. I suspect the policy bot is just misconfigured.

2023-09-07 18:35 UTC, merged